apiVersion: v1
kind: Pod
metadata:
  name: {{ .Chart.Name }}-{{ .Release.Namespace }}
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  containers:
    - name: busybox
      image: busybox
      resources:
        limits:
          memory: "128Mi"
          cpu: "250m"
      stdin: true
---
apiVersion: v1
kind: Pod
metadata:
  name: {{ .Chart.Name }}-ns-1
  namespace: ns-1
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  containers:
    - name: busybox
      image: busybox
      resources:
        limits:
          memory: "128Mi"
          cpu: "250m"
      stdin: true
